In [2]:
# 문제 1.
# mtcars 데이터셋의 mpg열 데이터의 평균이 20과 같다고 할 수 있는지 검정하시오.
# (유의수준 5%)
# H0 : mpg 열의 평균이 20과 같다(μ = 20)
# H1 : mpg 열의 평균이 20과 같지 않다(μ ≠ 20)

import pandas as pd
import numpy as np
# 데이터 불러오기 mtcars
mtcars_1 = pd.read_csv("mtcars.csv")

# 1-1) 정규성 검정을 실시하시오.
# 1-2) t검정을 실시하고 검정통계량을 구하시오.
# 1-3) p-value값을 구하시오.
# 1-4) 귀무가설 채택/기각 여부를 결정하시오.

In [3]:
# 1-1) 정규성 검정을 실시하시오.

# H0 = 정규분포를 따른다
# H1 = 정규분포를 따르지않는다
import scipy.stats as stats     # scipy.stats 모듈의 shapiro(정규성)검정을 불러온다(기억하기)
from scipy.stats import shapiro

statistic, pvalue = stats.shapiro(mtcars_1['mpg']) # mpg 칼럼의 정규성 검정(파라미터 두개 : 순서대로 통계랑, pvalue)
print(round(statistic,4))
print(round(pvalue,4))

result = stats.shapiro(mtcars_1['mpg'])   # mpg 칼럼의 정규성 검정(파라미터 한개 : 검정결과(result))
print(result)         # 검정결과: pvalue가 유의수준(0.05)보다 크므로 귀무가설을 채택한다(정규성을 따른다)

0.9476
0.1229
ShapiroResult(statistic=0.9475647265971182, pvalue=0.12288135948636081)


In [4]:
# 1-2) t검정을 실시하고 검정통계량을 구하시오.

# H0 : mpg 열의 평균이 20과 같다(μ = 20)
# H1 : mpg 열의 평균이 20과 같지 않다(μ ≠ 20)

from scipy.stats import ttest_1samp
statistic, pvalue = stats.ttest_1samp(mtcars_1['mpg'], popmean=20, alternative='two-sided')
print(round(statistic,4))


0.0851


In [5]:
# 1-3) p-value값을 구하시오.

print(round(pvalue,4))

0.9328


In [6]:
# 1-4) 귀무가설 채택/기각 여부를 결정하시오.

# 귀무가설 채택(pvalue값이 유의수준(0.05)보다 크다

In [7]:
# 문제 2.
# mtcars 데이터셋의 mpg열 데이터의 평균이 17보다 크다고 할 수 있는지 검정하시오.
# (유의수준 5%)
# H0 : mpg 열의 평균이 17보다 작거나 같다(μ <= 17)
# H1 : mpg 열의 평균이 17보다 크다(μ > 17)

import pandas as pd
import numpy as np
# 데이터 불러오기 mtcars
mtcars_2 = pd.read_csv("mtcars.csv")

# 2-1) 정규성 검정을 실시하시오.
# 2-2) t검정을 실시하고 검정통계량을 구하시오.
# 2-3) p-value값을 구하시오.
# 2-4) 귀무가설 채택/기각 여부를 결정하시오

In [8]:
# 2-1) 정규성 검정을 실시하시오.

# H0 = 정규분포를 따른다
# H1 = 정규분포를 따르지않는다

import scipy.stats as stats
from scipy.stats import shapiro

statistic, pvalue = stats.shapiro(mtcars_2['mpg'])
print(round(statistic,4))
print(round(pvalue,4))

# pvalue가 유의수준(0.05)보다 크므로 귀무가설 채택(정규성 만족)

0.9476
0.1229


In [9]:
# 2-2) t검정을 실시하고 검정통계량을 구하시오.

# H0 : mpg 열의 평균이 17보다 작거나 같다(μ <= 17)
# H1 : mpg 열의 평균이 17보다 크다(μ > 17)

from scipy.stats import ttest_1samp

statistic, pvalue = stats.ttest_1samp(mtcars_2['mpg'], popmean=17, alternative='greater')
print(round(statistic,4))


2.9008


In [10]:
# 2-3) p-value값을 구하시오.

print(round(pvalue,4))

0.0034


In [11]:
# 2-4) 귀무가설 채택/기각 여부를 결정하시오

# 귀무가설 기각(pvalue값이 유의수준(0.05)보다 작으므로 귀무가설을 기각한다) : 대립가설 채택

In [12]:
# 문제 3.
# mtcars 데이터셋의 mpg열 데이터의 평균이 17보다 작다고 할 수 있는지 검정하시오.
# (유의수준 5%)
# H0 : mpg 열의 평균이 17보다 크거나 같다(μ >= 17)
# H1 : mpg 열의 평균이 17보다 작다(μ < 17) 

import pandas as pd
import numpy as np
# 데이터 불러오기 mtcars
mtcars_3 = pd.read_csv("mtcars.csv")

# 3-1) 정규성 검정을 실시하시오.
# 3-2) t검정을 실시하고 검정통계량을 구하시오.
# 3-3) p-value값을 구하시오.
# 3-4) 귀무가설 채택/기각 여부를 결정하시오.

In [13]:
# 3-1) 정규성 검정을 실시하시오.

# H0 = 정규분포를 따른다
# H1 = 정규분포를 따르지않는다

import scipy.stats as stats
from scipy.stats import shapiro

statistic, pvalue = stats.shapiro(mtcars_3['mpg'])
print(round(statistic,4))
print(round(pvalue,4))  # 정규성만족(대립가설 채택)

0.9476
0.1229


In [14]:
# 3-2) t검정을 실시하고 검정통계량을 구하시오.

# H0 : mpg 열의 평균이 17보다 크거나 같다(μ >= 17)
# H1 : mpg 열의 평균이 17보다 작다(μ < 17) 

from scipy.stats import ttest_1samp

statistic, pvalue = stats.ttest_1samp(mtcars_3['mpg'], popmean=17, alternative='less')
print(round(statistic,4))

2.9008


In [15]:
# 3-3) p-value값을 구하시오.

print(round(pvalue,4))

0.9966


In [16]:
# 3-4) 귀무가설 채택/기각 여부를 결정하시오.

# 귀무가설 채택(대립가설 기각) 

In [17]:
# 문제 4.
# 다음은 혈압약을 먹은 전,후의 혈압 데이터이다.
# 혈압약을 먹기 전, 후의 차이가 있는지 쌍체 t 검정을 실시하시오.
# (유의수준 5%)
# before : 혈압약을 먹기 전 혈압, after : 혈압약을 먹은 후의 혈압
# H0(귀무가설) : after - before = 0
# H1(대립가설) : after - before ≠ 0

import pandas as pd
import numpy as np
# 데이터 만들기
medicine_1 = pd.DataFrame({
'before': [120, 135, 122, 124, 135, 122, 145, 160, 155, 142, 144, 135, 167],
'after' : [110, 132, 123, 119, 123, 115, 140, 162, 142, 138, 135, 142, 160] })
print(medicine_1.head(3))

# 4-1) 차이값에 대한 정규성 검정을 실시하고 p-value 값을 구하시오.
# 4-2) 쌍체t 검정을 실시하고 검정통계량과 p-value 값을 구하시오.
# 4-3) 귀무가설 채택/기각 여부를 결정하시오.

   before  after
0     120    110
1     135    132
2     122    123


In [18]:
# 4-1) 차이값에 대한 정규성 검정을 실시하고 p-value 값을 구하시오.

import scipy.stats as stats
from scipy.stats import shapiro

statistic, pvalue = stats.shapiro( medicine_1['after'] - medicine_1['before'] )
print(round(statistic,4))
print(round(pvalue,4))

# 귀무가설 채택 - 정규성 만족


0.9589
0.7363


In [19]:
# 4-2) 쌍체t 검정을 실시하고 검정통계량과 p-value 값을 구하시오.

from scipy.stats import ttest_rel

statistic, pvalue = stats.ttest_rel(medicine_1['after'], medicine_1['before'], alternative='two-sided')
print(round(statistic,4))
print(round(pvalue,4))

-3.1382
0.0086


In [20]:
# 4-3) 귀무가설 채택/기각 여부를 결정하시오.

# 귀무가설 기각(대립가설 채택)

In [21]:
# 문제 5.
# 다음은 혈압약을 먹은 전,후의 혈압 데이터이다.
# 혈압약을 먹은 후 혈압이 감소했는지 확인하기 위해 쌍체 t 검정을 실시하시오.
# (유의수준 5%)
# before : 혈압약을 먹기 전 혈압, after : 혈압약을 먹은 후의 혈압
# H0(귀무가설) : after - before >= 0
# H1(대립가설) : after - before < 0

# 데이터 만들기
medicine_2 = pd.DataFrame( {
'before': [120, 135, 122, 124, 135, 122, 145, 160, 155, 142, 144, 135, 167],
'after' : [110, 132, 123, 119, 123, 115, 140, 162, 142, 138, 135, 142, 160]})
print(medicine_2.head(3))

# 5-1) 차이값에 대한 정규성 검정을 실시하고 p-value 값을 구하시오.
# 5-2) 쌍체t 검정을 실시하고 검정통계량과 p-value 값을 구하시오.
# 5-3) 귀무가설 채택/기각 여부를 결정하시오.

   before  after
0     120    110
1     135    132
2     122    123


In [44]:
# 5-1) 차이값에 대한 정규성 검정을 실시하고 p-value 값을 구하시오.

import scipy.stats as stats
from scipy.stats import shapiro

statistic, pvalue = stats.shapiro(medicine_2['after']-medicine_2['before'])
print(round(statistic,4))
print(round(pvalue,4))

# 귀무가설 채택(정규성 만족)

0.9589
0.7363


In [45]:
# 5-2) 쌍체t 검정을 실시하고 검정통계량과 p-value 값을 구하시오.

# H0(귀무가설) : after - before >= 0
# H1(대립가설) : after - before < 0

from scipy.stats import ttest_rel

statistic, pvalue = stats.ttest_rel(medicine_2['after'], medicine_2['before'], alternative = 'less')

print(round(statistic,4))
print(round(pvalue,4))


-3.1382
0.0043


In [46]:
# 5-3) 귀무가설 채택/기각 여부를 결정하시오.

# 귀무가설 기각(대립가설 채택)

In [25]:
# 문제 6.
# 다음은 A그룹과 B그룹 인원의 혈압 데이터이다.
# 두 그룹의 혈압평균이 다르다고 할 수 있는지 독립표본 t검정을 실시하시오.
# (유의수준 5%)
# A : A그룹 인원의 혈압, B : B그룹 인원의 혈압
# H0(귀무가설) : A = B
# H1(대립가설) : A ≠ B

# 데이터 만들기
blood_1 = pd.DataFrame( {
'A': [120, 135, 122, 124, 135, 122, 145, 160, 155, 142, 144, 135, 167],
'B' : [110, 132, 123, 119, 123, 115, 140, 162, 142, 138, 135, 142, 160] })
print(blood_1.head(3))

# 6-1) 각 그룹 데이터가 정규성을 따르는지 검정하시오.
# 6-2) 각 그룹 데이터가 등분산성을 따르는지 검정하시오.
# 6-3) 독립표본t 검정을 실시하고 검정통계량과 p-value 값을 구하시오.
# 6-4) 귀무가설 채택/기각 여부를 결정하시오.

     A    B
0  120  110
1  135  132
2  122  123


In [48]:
# 6-1) 각 그룹 데이터가 정규성을 따르는지 검정하시오

import scipy.stats as stats
from scipy.stats import shapiro

statisticA, pvalueA = stats.shapiro(blood_1['A'])
statisticB, pvalueB = stats.shapiro(blood_1['B'])

print(round(statisticA,4), round(pvalueA,4))
print(round(statisticB,4), round(pvalueB,4))

# 귀무가설 채택(정규성 만족)

0.9314 0.3558
0.9498 0.5956


In [49]:
# 6-2) 각 그룹 데이터가 등분산성을 따르는지 검정하시오.

from scipy.stats import bartlett

statistic, pvalue = stats.bartlett(blood_1['A'], blood_1['B'])
print(round(statistic,4), round(pvalue,4))

# 귀무가설 채택(등분산성 만족)

0.0279 0.8673


In [50]:
# 6-3) 독립표본t 검정을 실시하고 검정통계량과 p-value 값을 구하시오.

# H0(귀무가설) : A = B
# H1(대립가설) : A ≠ B

from scipy.stats import ttest_ind

statistic, pvalue = stats.ttest_ind(blood_1['A'], blood_1['B'],
                                    equal_var=True,
                                    alternative='two-sided')

print(round(statistic,4), round(pvalue,4))


0.8192 0.4207


In [29]:
# 6-4) 귀무가설 채택/기각 여부를 결정하시오.

# 귀무가설 채택(pvalue가 유의수준보다 크다)

In [30]:
# 문제 7.
# 다음은 A그룹과 B그룹 인원의 혈압 데이터이다. A그룹의 혈압 평균이 B그룹보다 크다고 할 수 있
# 는지 독립표본 t검정을 실시하시오. (유의수준 5%)
# A : A그룹 인원의 혈압, B : B그룹 인원의 혈압
# H0(귀무가설) : A - B ≤ 0 ( or A ≤ B)
# H1(대립가설) : A - B > 0 ( or A > B)

# 데이터 만들기
blood_2 = pd.DataFrame( {
'A': [120, 135, 122, 124, 135, 122, 145, 160, 155, 142, 144, 135, 167],
'B' : [110, 132, 123, 119, 123, 115, 140, 162, 142, 138, 135, 142, 160] })
print(blood_2.head(3))

# 7-1) 각 그룹 데이터가 정규성을 따르는지 검정하시오.
# 7-2) 각 그룹 데이터가 등분산성을 따르는지 검정하시오.
# 7-3) 독립표본t 검정을 실시하고 검정통계량과 p-value 값을 구하시오.
# 7-4) 귀무가설 채택/기각 여부를 결정하시오.

     A    B
0  120  110
1  135  132
2  122  123


In [52]:
# 7-1) 각 그룹 데이터가 정규성을 따르는지 검정하시오.

from scipy.stats import shapiro

statisticA, pvalueA = stats.shapiro(blood_2['A'])
statisticB, pvalueB = stats.shapiro(blood_2['B'])
print(round(statisticA,4), round(pvalueA,4))
print(round(statisticB,4), round(pvalueB,4))

# 정규성만족(대립가설채택)

0.9314 0.3558
0.9498 0.5956


In [53]:
# 7-2) 각 그룹 데이터가 등분산성을 따르는지 검정하시오.

from scipy.stats import bartlett

staticmethod, pvalue = stats.bartlett(blood_2['A'], blood_2['B'])
print(round(statistic,4), round(pvalue,4))

# 등분산성만족(대립가설채택)

0.8192 0.8673


In [54]:
# 7-3) 독립표본t 검정을 실시하고 검정통계량과 p-value 값을 구하시오.

# H0(귀무가설) : A - B ≤ 0 ( or A ≤ B)
# H1(대립가설) : A - B > 0 ( or A > B)

from scipy.stats import ttest_ind

statistic, pvalue = stats.ttest_ind(blood_2['A'], blood_2['B'],
                                    equal_var=True,
                                    alternative='greater')

print(round(statistic,4), round(pvalue,4))


0.8192 0.2104


In [ ]:
# 7-4) 귀무가설 채택/기각 여부를 결정하시오.

# 귀무가설 채택(pvalue가 유의수준보다 크다)

In [1]:
# 문제 8.
# 다음은 A, B, C 그룹 인원 성적 데이터이다.
# 세 그룹의 성적 평균이 같다고 할 수 있는지 ANOVA 분석을 실시하시오.
# (유의수준 5%)
# A, B, C : 각 그룹 인원의 성적
# H0(귀무가설) : A(평균) = B(평균) = C(평균)
# H1(대립가설) : Not H0 (적어도 하나는 같지 않다)

import pandas as pd
import numpy as np
# 데이터 만들기
score = pd.DataFrame( {
'A': [120, 135, 122, 124, 135, 122, 145, 160, 155, 142, 144, 135, 167],
'B' : [110, 132, 123, 119, 123, 115, 140, 162, 142, 138, 135, 142, 160],
'C' : [130, 120, 115, 122, 133, 144, 122, 120, 110, 134, 125, 122, 122]})
print(score.head(3))

# 8-1) 각 그룹 데이터가 정규성을 따르는지 검정하시오.
# 8-2) 각 그룹 데이터가 등분산성을 따르는지 검정하시오.
# 8-3) 독립표본t 검정을 실시하고 검정통계량과 p-value 값을 구하시오.
# 8-4) 귀무가설 채택/기각 여부를 결정하시오.

     A    B    C
0  120  110  130
1  135  132  120
2  122  123  115


In [3]:
# 8-1) 각 그룹 데이터가 정규성을 따르는지 검정하시오.

import scipy.stats as stats
from scipy.stats import shapiro

print(stats.shapiro(score['A']))
print(stats.shapiro(score['B']))
print(stats.shapiro(score['C']))

# 정규성 만족

ShapiroResult(statistic=0.9314373738322363, pvalue=0.35584957364120257)
ShapiroResult(statistic=0.9498199298581277, pvalue=0.5955637454032426)
ShapiroResult(statistic=0.9396706636806645, pvalue=0.4526517552551474)


In [5]:
# 8-2) 각 그룹 데이터가 등분산성을 따르는지 검정하시오.

from scipy.stats import bartlett

print(stats.bartlett(score['A'], score['B'], score['C']))

# 등분산성 만족

BartlettResult(statistic=4.222248448848066, pvalue=0.12110174433684852)


In [6]:
# 8-3) 독립표본t 검정을 실시하고 검정통계량과 p-value 값을 구하시오.

from scipy.stats import f_oneway

statistic, pvalue = stats.f_oneway(score['A'], score['B'], score['C'])

print(round(statistic,4), round(pvalue,4))

3.6971 0.0346


In [ ]:
# 8-4) 귀무가설 채택/기각 여부를 결정하시오.

#귀무가설 기각(대립가설 채택)

In [32]:
# 문제 9.    
# 랜덤 박스에 상품 A,B,C,D가 들어있다.
# 다음은 랜덤박스에서 100번 상품을 꺼냈을 때의 상품 데이터라고 할 때
# 상품이 동일한 비율로 들어있다고 할 수 있는지 검정해보시오.       -----> 카이제곱 검정(적합도 검정:chisquare) <--------
# A=30, B=20, C=15, D=35

import pandas as pd
import numpy as np
# 데이터 생성
row1 = [30, 20, 15, 35]
box_1 = pd.DataFrame([row1], columns=['A','B','C', 'D'])
box_1

# 9-1) 관측빈도와 기대빈도를 구하시오.
# 9-2) 카이제곱검정을 실시하고 검정통계량과 p-value 값을 구하시오.
# 9-3) 귀무가설 채택/기각 여부를 결정하시오.

In [13]:
# 9-1) 관측빈도와 기대빈도를 구하시오.

f_obs = [30, 20, 15, 35]
f_exp = [25, 25, 25, 25]


In [12]:
# 9-2) 카이제곱검정을 실시하고 검정통계량과 p-value 값을 구하시오.
from scipy.stats import chisquare

statistic, pvalue = stats.chisquare(f_obs=f_obs, f_exp=f_exp)
print(statistic)
print(pvalue)           # 자유도는 n-1 = 3 

10.0
0.01856613546304325


In [7]:
# 9-3) 귀무가설 채택/기각 여부를 결정하시오.

# 귀무가설기각


In [8]:
# 문제 10.
# 랜덤 박스에 상품 A, B, C가 들어있다.
# 다음은 랜덤박스에서 150번 상품을 꺼냈을 때의 상품 데이터라고 할 때
# 상품별로 A 30%, B 15%, C 55% 비율로 들어있다고 할 수 있는지 검정해보시오.       -----> 카이제곱 검정(독립성 검정:chi2_contingency) <--------
# A=50, B=25, C=75

import pandas as pd
import numpy as np
# 데이터 생성
row1 = [50,25,75]
box_2 = pd.DataFrame([row1], columns=['A','B','C'])
box_2

# 10-1) 관측빈도와 기대빈도를 구하시오.
# 10-2) 카이제곱검정을 실시하고 검정통계량과 p-value 값을 구하시오.
# 10-3) 귀무가설 채택/기각 여부를 결정하시오.

A   B   C
0  50  25  75

In [15]:
# 10-1) 관측빈도와 기대빈도를 구하시오.

f_obs = [50, 25, 75]

a = 150 * 0.3
b = 150 * 0.15
c = 150* 0.55

f_exp = [a, b, c]


In [16]:
# 10-2) 카이제곱검정을 실시하고 검정통계량과 p-value 값을 구하시오.

statistic, pvalue = chisquare(f_obs=f_obs, f_exp=f_exp)
print(statistic)
print(pvalue)

1.5151515151515151
0.46880153914023537


In [17]:
# 10-3) 귀무가설 채택/기각 여부를 결정하시오.

# 귀무가설 채택(대립가설 기각)

In [9]:
# 문제 11.
# 연령대에 따라 먹는 아이스크림의 차이가 있는지 독립성 검정을 실시하시오.

import pandas as pd
import numpy as np
# 데이터 생성
row1, row2 = [200, 190, 250], [220, 250, 300]
icecream = pd.DataFrame([row1, row2], columns=['딸기','초코','바닐라'], index=['10대','20대'])
icecream

# 11-1) 관측빈도와 기대빈도를 구하시오.
# 11-2) 카이제곱검정을 실시하고 검정통계량과 p-value 값을 구하시오.
# 11-3) 귀무가설 채택/기각 여부를 결정하시오.

딸기   초코  바닐라
10대  200  190  250
20대  220  250  300

In [ ]:
# 11-1) 관측빈도와 기대빈도를 구하시오.


In [18]:
# 11-2) 카이제곱검정을 실시하고 검정통계량과 p-value 값을 구하시오.

from scipy.stats import	chi2_contingency
 
statistic, pvalue, dof,	expected = chi2_contingency(icecream)
 
print(statistic)
print(pvalue)
print(dof)			#	자유도 = (행-1)*(열-1)
print(np.round(expected, 2))	#	반올림하고	싶다면	np.round()

#	(참고)	print(chi2_contingency(df))

1.708360126075226
0.4256320394874311
2
[[190.64 199.72 249.65]
 [229.36 240.28 300.35]]


In [ ]:
# 11-3) 귀무가설 채택/기각 여부를 결정하시오.

# 귀무가설 채택(연령대와 먹는 아이스크림의 종류는 서로 관련이 없다고 할 수 있다)

In [22]:
######### (추가)	만약	데이터	형태가	다를경우?
icecream_2	=	pd.DataFrame({
'아이스크림'	:	['딸기','초코','바닐라','딸기','초코','바닐라'],
'연령'	:	['10대','10대','10대','20대','20대','20대'],
'인원'	:	[200,190,250,220,250,300]
})

table	=	pd.crosstab(index=icecream_2['연령'],	columns=icecream_2['아이스크림'],	values=icecream_2['인원'],	aggfunc=sum)
table

###	주의 : index, columns에 순서 꼭 확인하기 ###


C:\Users\admin\AppData\Local\Temp\ipykernel_19676\1862271488.py:8: FutureWarning: The provided callable <built-in function sum> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  table	=	pd.crosstab(index=icecream_2['연령'],	columns=icecream_2['아이스크림'],	values=icecream_2['인원'],	aggfunc=sum)


아이스크림   딸기  바닐라   초코
연령                  
10대    200  250  190
20대    220  300  250

In [23]:
from scipy.stats import chi2_contingency

statistic, pvalue, dof, expected = chi2_contingency(table)

print(statistic)
print(pvalue)
print(dof)
print(np.round(expected, 2))

1.708360126075226
0.4256320394874311
2
[[190.64 249.65 199.72]
 [229.36 300.35 240.28]]


In [10]:
# 문제 12.
# 타이타닉에 데이터에서 성별(sex)과 생존여부(survived) 변수간 독립성 검정을 실시하시오.

import seaborn as sns
titanic = sns.load_dataset('titanic')
titanic.head(3)

# 12-1) 관측빈도와 기대빈도를 구하시오.
# 12-2) 카이제곱검정을 실시하고 검정통계량과 p-value 값을 구하시오.
# 12-3) 귀무가설 채택/기각 여부를 결정하시오.

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True

In [24]:
# 12-1) 관측빈도와 기대빈도를 구하시오.

table = pd.crosstab(titanic['sex'], titanic['survived'])
print(table)

survived    0    1
sex               
female     81  233
male      468  109


In [25]:
# 12-2) 카이제곱검정을 실시하고 검정통계량과 p-value 값을 구하시오.

# H0 : 성별과 생존 여부는 서로 관련이 없다(두 변수는 서로 독립이다.)
# H1 : 성별과 생존 여부는 서로 관련이 있다(두 변수는 서로 독립이 아니다.)

from scipy.stats import chi2_contingency

statistic, pvalue, dof, expected = stats.chi2_contingency(table)

print(statistic)
print(pvalue)
print(dof)
print(np.round(expected, 2))

260.71702016732104
1.1973570627755645e-58
1
[[193.47 120.53]
 [355.53 221.47]]


In [ ]:
# 12-3) 귀무가설 채택/기각 여부를 결정하시오.

# 귀무가설 채택(대립가설 기각)
#   => 성별과 생존여부는 서로 관련이 없다고 할 수 있다.