In [1]:
# 모의고사 2유형
# 2유형 3번(와인 종류 분류)
# 제공된 데이터는 와인의 조성 데이터를 기반으로 해당 와인이 어떤 종류의 와인인지 분류한 데이
# 터셋이다. 학습 데이터(train)를 이용하여 와인의 종류을 분류하는 모델을 개발하고 해당 모델을
# 기반으로 평가 데이터(test)를 적용하여 얻은 예측결과를 아래 제출 양식에 맞추어 CSV 파일로 제
# 출하시오.
# 예측결과는 Accuracy, macro F1 score 지표로 평가함
# 제출형식 (아래 예시)
#  csv파일명 : result.csv
# 예측 진척정도 칼럼명 : pred
# 제출 칼럼 개수 : pred 칼럼 1개 (아래)

# # 예시자료(result 결과값과 같은 형태로 제출)
#  import pandas as pd
#  result = pd.DataFrame({'pred':[1,0,2]})
#  result
#  # 아래 코드는 예시이며 변수명 등 개인별로 변경하여 활용
# # pd.DataFrame변수.to_csv("result.csv", index=False)

# 데이터 설명
# 1. 변수설명
# class : 와인의 종류, 종속변수(0, 1, 2)
# 그 외 변수 : 와인의 특징을 나타내는 독립변수(Xs)
#  1. 학습/평가 데이터
# train : 학습 데이터
# test : 평가 데이터(taget 변수 제외)
#  y_test : 평가 데이터(target 변수 only) / 단, 실제 시험에서는 주어지지 않음

In [2]:
###############  실기환경 복사 영역  ###############
import pandas as pd
import numpy as np

# 실기 시험 데이터셋으로 셋팅하기 (수정금지)
from sklearn.datasets import load_wine
# 와인 데이터셋 load 
X, y = load_wine(return_X_y= True, as_frame=True)

# 실기 시험 데이터셋으로 셋팅하기 (수정금지)
from sklearn.model_selection import train_test_split
x_tr, x_te, y_tr, y_te = train_test_split(X, y, test_size=0.2,
                                          stratify=y,
                                          random_state=2024)
test = pd.DataFrame(x_te)
x_tr = pd.DataFrame(x_tr)
y_tr = pd.DataFrame(y_tr)
y_tr.columns = ['class'] 
y_test = pd.DataFrame(y_te)
train = pd.concat([y_tr, x_tr], axis=1)

train['hue'] = np.where(train['hue']>=1, 'H', 'L')
test['hue'] = np.where(test['hue']>=1, 'H', 'L')
train.iloc[0:3, train.columns.get_loc('alcohol')] = np.nan
test.iloc[0:3, test.columns.get_loc('alcohol')] = np.nan
###############  실기환경 복사 영역  ###############

In [3]:
train.head()

class  alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  \
39       0      NaN        3.99  2.51               13.2      128.0   
83       1      NaN        3.86  2.32               22.5       85.0   
68       1      NaN        0.94  2.36               17.0      110.0   
151      2    12.79        2.67  2.48               22.0      112.0   
167      2    12.82        3.37  2.30               19.5       88.0   

     total_phenols  flavanoids  nonflavanoid_phenols  proanthocyanins  \
39            3.00        3.04                  0.20             2.08   
83            1.65        1.59                  0.61             1.62   
68            2.53        1.30                  0.55             0.42   
151           1.48        1.36                  0.24             1.26   
167           1.48        0.66                  0.40             0.97   

     color_intensity hue  od280/od315_of_diluted_wines  proline  
39              5.10   L                          3.53    760.0  
83              4.80   L                          2.01    515.0  
68              3.17   H                          1.93    750.0  
151            10.80   L                          1.47    480.0  
167            10.26   L                          1.75    685.0

In [4]:
test.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
81       NaN        1.81  2.20               18.8       86.0           2.20   
88       NaN        2.06  2.46               21.6       84.0           1.95   
134      NaN        1.24  2.25               17.5       85.0           2.00   
35     13.48        1.81  2.41               20.5      100.0           2.70   
41     13.41        3.84  2.12               18.8       90.0           2.45   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity hue  \
81         2.53                  0.26             1.77             3.90   H   
88         1.69                  0.48             1.35             2.80   H   
134        0.58                  0.60             1.25             5.45   L   
35         2.98                  0.26             1.86             5.10   H   
41         2.68                  0.27             1.48             4.28   L   

     od280/od315_of_diluted_wines  proline  
81                           3.14    714.0  
88                           2.75    680.0  
134                          1.51    650.0  
35                           3.47    920.0  
41                           3.00   1035.0

In [5]:
train.shape

(142, 14)

In [6]:
test.shape

(36, 13)

In [7]:
train.isnull().sum()

class                           0
alcohol                         3
malic_acid                      0
ash                             0
alcalinity_of_ash               0
magnesium                       0
total_phenols                   0
flavanoids                      0
nonflavanoid_phenols            0
proanthocyanins                 0
color_intensity                 0
hue                             0
od280/od315_of_diluted_wines    0
proline                         0
dtype: int64

In [8]:
test.isnull().sum()

alcohol                         3
malic_acid                      0
ash                             0
alcalinity_of_ash               0
magnesium                       0
total_phenols                   0
flavanoids                      0
nonflavanoid_phenols            0
proanthocyanins                 0
color_intensity                 0
hue                             0
od280/od315_of_diluted_wines    0
proline                         0
dtype: int64

In [9]:
median1 = train['alcohol'].median()
median2 = test['alcohol'].median()

train['alcohol'] = train['alcohol'].fillna(median1)
test['alcohol'] = test['alcohol'].fillna(median2)

In [10]:
print(train.isnull().sum())
print(test.isnull().sum())

class                           0
alcohol                         0
malic_acid                      0
ash                             0
alcalinity_of_ash               0
magnesium                       0
total_phenols                   0
flavanoids                      0
nonflavanoid_phenols            0
proanthocyanins                 0
color_intensity                 0
hue                             0
od280/od315_of_diluted_wines    0
proline                         0
dtype: int64
alcohol                         0
malic_acid                      0
ash                             0
alcalinity_of_ash               0
magnesium                       0
total_phenols                   0
flavanoids                      0
nonflavanoid_phenols            0
proanthocyanins                 0
color_intensity                 0
hue                             0
od280/od315_of_diluted_wines    0
proline                         0
dtype: int64


In [11]:
train['hue'].unique()

array(['L', 'H'], dtype=object)

In [12]:
test['hue'].unique()

array(['H', 'L'], dtype=object)

In [14]:
train = pd.get_dummies(train)
test = pd.get_dummies(test)
print(train.head())
print(test.head())

     class  alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  \
39       0    13.05        3.99  2.51               13.2      128.0   
83       1    13.05        3.86  2.32               22.5       85.0   
68       1    13.05        0.94  2.36               17.0      110.0   
151      2    12.79        2.67  2.48               22.0      112.0   
167      2    12.82        3.37  2.30               19.5       88.0   

     total_phenols  flavanoids  nonflavanoid_phenols  proanthocyanins  \
39            3.00        3.04                  0.20             2.08   
83            1.65        1.59                  0.61             1.62   
68            2.53        1.30                  0.55             0.42   
151           1.48        1.36                  0.24             1.26   
167           1.48        0.66                  0.40             0.97   

     color_intensity  od280/od315_of_diluted_wines  proline  hue_H  hue_L  
39              5.10                          3.53    760.

In [20]:
from sklearn.model_selection import train_test_split

x = train.drop(columns='class')
y = train['class']



In [21]:
x_train, x_val, y_train, y_val = train_test_split(x, y, test_size = 0.2, stratify=y, random_state=2024)

print(x_train.shape)
print(y_train.shape)
print(x_val.shape)
print(y_val.shape)

(113, 14)
(113,)
(29, 14)
(29,)


In [22]:
from sklearn.ensemble import RandomForestClassifier

rfc = RandomForestClassifier(random_state=2024)
model = rfc.fit(x_train, y_train)
pred = model.predict(x_val)


In [23]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

acc = accuracy_score(y_val, pred)
rpt = classification_report(y_val, pred)
matrix = confusion_matrix(y_val, pred)

In [24]:
print(acc, rpt, matrix)

0.9655172413793104               precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       1.00      0.92      0.96        12
           2       0.89      1.00      0.94         8

    accuracy                           0.97        29
   macro avg       0.96      0.97      0.97        29
weighted avg       0.97      0.97      0.97        29
 [[ 9  0  0]
 [ 0 11  1]
 [ 0  0  8]]


In [27]:
pred2 = model.predict(test)

acc2 = accuracy_score(y_test, pred2)
rpt2 = classification_report(y_test, pred2)
matrix2 = confusion_matrix(y_test, pred2)

print(acc2, rpt2, matrix2)

1.0               precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00        14
           2       1.00      1.00      1.00        10

    accuracy                           1.00        36
   macro avg       1.00      1.00      1.00        36
weighted avg       1.00      1.00      1.00        36
 [[12  0  0]
 [ 0 14  0]
 [ 0  0 10]]
