In [1]:
# 모의고사 2유형
# 2유형 1번(악성종양 분류)
# 제공된 데이터는 종양의 크기, 모양 등 다양한 변수를 기반으로 해당 종양이 악성종양(malignant)
# 인지 양성종양(benign)인지 분류한 데이터셋이다. 학습 데이터(train)를 이용하여 악성종양을 분
# 류하는 모델을 개발하고 해당 모델을 기반으로 평가 데이터(test)를 적용하여 얻은 예측결과를 아
# 래 제출 양식에 맞추어 CSV 파일로 제출하시오.
# 단, 예측결과는 악성종양(0)일 확률값을 제출하시오.
# 예측결과는 Accuracy, ROC-AUC 지표로 평가함.
# (실제 시험에서는 test셋의 y값이 주어지지 않으나,
# 해당 모의고사에서는 본인이 직접 y_test 값을 이용하여 성능평가 해보시오)
# 제출형식 (아래 예시)
# csv파일명 : result.csv
# 예측 종양 칼럼명 : pred
# 제출 칼럼 개수 : pred 칼럼 1개 (아래)

In [2]:
# 예시자료(result 결과값과 같은 형태로 제출)
# import pandas as pd
# result = pd.DataFrame({'pred':[0.7, 0.2, 0.3]})
# result
# # 아래 코드는 예시이며 변수명 등 개인별로 변경하여 활용
# pd.DataFrame변수.to_csv("result.csv", index=False)

# 데이터 설명
# 1. 변수설명
# 종속변수(Y) : target 칼럼(0 : 악성종양, 1 : 양성종양)
# 독립변수(X) : no, target을 제외한 칼럼
# 종양번호 : no 칼럼

In [3]:
###############  실기환경    복사    영역  ############### 
import pandas as pd
import numpy as np
# 실기    시험    데이터셋으로    셋팅하기 (수정금지)
from sklearn.datasets import    load_breast_cancer 
# 유방암    데이터셋 load
cancer = load_breast_cancer()
X, y = load_breast_cancer(return_X_y=    True, as_frame=True) 
# 실기    시험    데이터셋으로    셋팅하기 (수정금지)
from sklearn.model_selection import train_test_split
x_tr, x_te, y_tr, y_te = train_test_split(X, y, test_size=0.2,
stratify=y, random_state=2024)
test = pd.DataFrame(x_te.reset_index()) 
y_test = pd.DataFrame(y_te.reset_index()) 
x_tr = pd.DataFrame(x_tr.reset_index()) 
y_tr = pd.DataFrame(y_tr.reset_index())
test.rename(columns={'index':'no'}, inplace=True) 
x_tr.rename(columns={'index':'no'}, inplace=True) 
y_test.columns = ['no', 'target']
y_tr.columns = ['no1', 'target']
train = pd.concat([y_tr, x_tr], axis=1) 
train = train.drop('no1', axis=1)
y_test = y_test.drop('no', axis=1) 
train.loc[0:2, 'mean radius'] = np.nan
###############  실기환경    복사    영역  ###############



In [4]:
 print(x_tr.head())
 print(y_tr.head())



    no  mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0  516       18.310         20.58          120.80     1052.0          0.10680   
1   71        8.888         14.64           58.79      244.0          0.09783   
2  277       18.810         19.98          120.90     1102.0          0.08923   
3   10       16.020         23.24          102.70      797.8          0.08206   
4   20       13.080         15.71           85.63      520.0          0.10750   

   mean compactness  mean concavity  mean concave points  mean symmetry  ...  \
0           0.12480         0.15690              0.09451         0.1860  ...   
1           0.15310         0.08606              0.02872         0.1902  ...   
2           0.05884         0.08020              0.05843         0.1550  ...   
3           0.06669         0.03299              0.03323         0.1528  ...   
4           0.12700         0.04568              0.03110         0.1967  ...   

   worst radius  worst texture  

In [5]:
print(x_tr.head())


    no  mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0  516       18.310         20.58          120.80     1052.0          0.10680   
1   71        8.888         14.64           58.79      244.0          0.09783   
2  277       18.810         19.98          120.90     1102.0          0.08923   
3   10       16.020         23.24          102.70      797.8          0.08206   
4   20       13.080         15.71           85.63      520.0          0.10750   

   mean compactness  mean concavity  mean concave points  mean symmetry  ...  \
0           0.12480         0.15690              0.09451         0.1860  ...   
1           0.15310         0.08606              0.02872         0.1902  ...   
2           0.05884         0.08020              0.05843         0.1550  ...   
3           0.06669         0.03299              0.03323         0.1528  ...   
4           0.12700         0.04568              0.03110         0.1967  ...   

   worst radius  worst texture  

In [6]:
print(y_tr.head())



   no1  target
0  516       0
1   71       1
2  277       0
3   10       0
4   20       1


In [7]:
x_tr = x_tr.drop(columns='no')
y_tr = y_tr.drop(columns='no1')

y_te = y_te.drop(columns='no')

In [8]:
print(x_te.head())

     mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
494        13.16         20.54           84.06      538.7          0.07335   
43         13.28         20.28           87.32      545.2          0.10410   
306        13.20         15.82           84.07      537.3          0.08511   
315        12.49         16.85           79.19      481.6          0.08511   
105        13.11         15.56           87.21      530.2          0.13980   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
494           0.05275        0.018000             0.012560         0.1713   
43            0.14360        0.098470             0.061580         0.1974   
306           0.05251        0.001461             0.003261         0.1632   
315           0.03834        0.004473             0.006423         0.1215   
105           0.17650        0.207100             0.096010         0.1925   

     mean fractal dimension  ...  worst radius  worst texture  \
494

In [9]:
print(x_tr.isnull().sum())

mean radius                0
mean texture               0
mean perimeter             0
mean area                  0
mean smoothness            0
mean compactness           0
mean concavity             0
mean concave points        0
mean symmetry              0
mean fractal dimension     0
radius error               0
texture error              0
perimeter error            0
area error                 0
smoothness error           0
compactness error          0
concavity error            0
concave points error       0
symmetry error             0
fractal dimension error    0
worst radius               0
worst texture              0
worst perimeter            0
worst area                 0
worst smoothness           0
worst compactness          0
worst concavity            0
worst concave points       0
worst symmetry             0
worst fractal dimension    0
dtype: int64


In [10]:
print(y_tr.isnull().sum())

target    0
dtype: int64


In [11]:
print(x_te.isnull().sum())

mean radius                0
mean texture               0
mean perimeter             0
mean area                  0
mean smoothness            0
mean compactness           0
mean concavity             0
mean concave points        0
mean symmetry              0
mean fractal dimension     0
radius error               0
texture error              0
perimeter error            0
area error                 0
smoothness error           0
compactness error          0
concavity error            0
concave points error       0
symmetry error             0
fractal dimension error    0
worst radius               0
worst texture              0
worst perimeter            0
worst area                 0
worst smoothness           0
worst compactness          0
worst concavity            0
worst concave points       0
worst symmetry             0
worst fractal dimension    0
dtype: int64


In [12]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(random_state=2024, penalty=None)
model.fit(x_tr, y_tr)
pred = model.predict(x_te)



C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [13]:
pred

array([1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 1])

In [14]:
pred = pd.DataFrame({'pred':pred})

In [15]:
y_te.reset_index(drop=True)

0      1
1      0
2      1
3      1
4      0
      ..
109    1
110    0
111    1
112    0
113    1
Name: target, Length: 114, dtype: int32

In [20]:
from sklearn.metrics import classification_report, confusion_matrix

rpt = classification_report(y_te, pred)
matrix = confusion_matrix(y_te, pred)
y_result_proba = model.predict_proba(x_te)

print(rpt)
print(matrix)
print(np.round(y_result_proba,2))


              precision    recall  f1-score   support

           0       0.92      0.83      0.88        42
           1       0.91      0.96      0.93        72

    accuracy                           0.91       114
   macro avg       0.91      0.90      0.90       114
weighted avg       0.91      0.91      0.91       114

[[35  7]
 [ 3 69]]
[[0.14 0.86]
 [0.92 0.08]
 [0.   1.  ]
 [0.   1.  ]
 [0.49 0.51]
 [0.11 0.89]
 [0.57 0.43]
 [0.01 0.99]
 [0.01 0.99]
 [0.76 0.24]
 [1.   0.  ]
 [0.01 0.99]
 [0.   1.  ]
 [1.   0.  ]
 [0.14 0.86]
 [0.   1.  ]
 [0.   1.  ]
 [0.98 0.02]
 [0.13 0.87]
 [0.5  0.5 ]
 [0.01 0.99]
 [0.   1.  ]
 [0.06 0.94]
 [1.   0.  ]
 [1.   0.  ]
 [0.96 0.04]
 [0.   1.  ]
 [0.04 0.96]
 [0.02 0.98]
 [0.06 0.94]
 [1.   0.  ]
 [1.   0.  ]
 [0.11 0.89]
 [0.58 0.42]
 [0.4  0.6 ]
 [0.01 0.99]
 [0.01 0.99]
 [0.   1.  ]
 [0.41 0.59]
 [0.   1.  ]
 [0.01 0.99]
 [0.   1.  ]
 [0.06 0.94]
 [0.   1.  ]
 [1.   0.  ]
 [1.   0.  ]
 [0.02 0.98]
 [0.07 0.93]
 [1.   0.  ]
 [0.   1.  ]
 [0.